# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product_event', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name_product_event', models.CharField(max_length=100)),
                ('price_product_evet', models.IntegerField()),
                ('id_event', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SaveTicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name_event', models.CharField(max_length=65)),
                ('status_event', models.CharField(max_length=65)),
                ('start_time_event', models.DateTimeField(unique_for_date='pub_date')),
                ('end_time_event', models.DateTimeField(unique_for_date='pub_date')),
                ('time_letter_event', models.CharField(max_length=100)),
                ('location_event', models.CharField(max_length=100)),
                ('fb_share_img_url_event', models.TextField()),
                ('description_event', models.TextField()),
                ('ticketshop_url_event', models.TextField()),
                ('sold_out_event', models.CharField(max_length=25)),
                ('organizer_event', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_event_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intoapp.ProductEvent')),
            ],
        ),
    ]
